name: CI
on: [ push ]
jobs:
  build_and_test:
    name: Rust Cargo Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libbluetooth-dev
          version: 1.0
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo clippy --all-targets --all-features -- --deny warnings
      - run: cargo check
      - run: cargo build --verbose --release --all-features
      - run: cargo test --verbose --all

  compile_check_macos:
    name: macOS Build + Sign Check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo build --release
      - run: codesign -s - --entitlements divoom.entitlements --force target/release/divoom-ditoo-pro-controller
      - run: codesign -dv target/release/divoom-ditoo-pro-controller
